image: node:12

stages:
  - validate
  - test
  - build
  - deploy

include:
  - project: 'eppendorf/infrastructure-tooling/ci-templates'
    ref: v0.1.0
    file: '/job-templates.yml'

validate:test:
  extends:
    - .validate_template
    - .tags_template
    - .npm_registry_template
  script:
    - yarn test:ci
  artifacts:
    paths:
      - ./reports
    reports:
      junit: ./reports/unit/junit.xml
      cobertura: ./reports/unit/cobertura-coverage.xml

code_quality:
  extends:
    - .validate_template
    - .tags_template
    - .npm_registry_template
  image: node:12
  script:
    - yarn lint:ci
  artifacts:
    reports:
      codequality: ./reports/lint/gl-codequality.json

build:
  stage: build
  extends:
    - .tags_template
    - .npm_registry_template
  variables:
    NODE_ENV: 'production'
  script:
    - yarn build
  artifacts:
    paths:
      - ./dist
    expire_in: 6 hours

deploy:
  stage: deploy
  extends:
    - .tags_template
    - .npm_registry_template
  only:
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?$/
  script:
    - echo '//git.dasgip.de/api/v4/projects/3/packages/npm/:_authToken=${NPM_REGISTRY_TOKEN}' >> ~/.npmrc
    - npm publish
