image: node:12

stages:
  - validate
  - test
  - build
  - deploy

variables:
  ESLINT_FORMATTER: gitlab
  ESLINT_CODE_QUALITY_REPORT: ./reports/lint/gl-codequality.json
  SAST_EXCLUDED_PATHS: 'node_modules'
  NPM_CONFIG_CACHE: /cache/.npm
  YARN_CACHE_FOLDER: /cache/.npm

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: License-Scanning.gitlab-ci.yml

.validate_template: &validate_definition
  stage: validate

.npm_registry_template: &npm_registry_definition
  before_script:
    - echo "//artifactory.cluster/artifactory/api/npm/npm_registry/:_password=${ARTIFACTORY_NPM_PASS}" >> ~/.npmrc
    - echo "//artifactory.cluster/artifactory/api/npm/npm_registry/:username=${ARTIFACTORY_NPM_USER}" >> ~/.npmrc
    - echo "strict-ssl=false" >> ~/.npmrc
    - echo "\"//artifactory.cluster/artifactory/api/npm/npm_registry/:_password=\" ${ARTIFACTORY_NPM_PASS}" >> ~/.yarnrc
    - echo "\"//artifactory.cluster/artifactory/api/npm/npm_registry/:username=\" ${ARTIFACTORY_NPM_USER}" >> ~/.yarnrc
    - echo "strict-ssl \"\"" >> ~/.yarnrc

validate:test:
  extends:
    - .validate_template
    - .npm_registry_template
  script:
    - yarn install --production=false --network-concurrency=1
    - yarn test:ci
  artifacts:
    paths:
      - ./reports
    reports:
      junit: ./reports/unit/junit.xml
      cobertura: ./reports/unit/cobertura-coverage.xml

code_quality:
  extends:
    - .validate_template
    - .npm_registry_template
  image: node:12
  script:
    - yarn install --production=false --network-concurrency=1
    - yarn lint:ci
  artifacts:
    reports:
      codequality: ./reports/lint/gl-codequality.json

build:
  stage: build
  extends:
    - .validate_template
    - .npm_registry_template
  variables:
    NODE_ENV: 'production'
  script:
    - yarn install --production=false --network-concurrency=1
    - yarn build
  artifacts:
    paths:
      - ./dist
    expire_in: 6 hours

deploy:
  stage: deploy
  extends:
    - .validate_template
    - .npm_registry_template
  only:
    - /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?$/
  script:
    - npm publish
  dependencies:
    - build
